# Generated by Django 3.1.1 on 2020-09-09 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteka',
            name='typ_okladki',
            field=models.CharField(choices=[('miekka', 'Okladka miekka'), ('twarda', 'Okladka twarda')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='biblioteka',
            name='uzytkownik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
