# Generated by Django 3.1.1 on 2020-09-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0002_auto_20200909_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteka',
            name='data_premiery',
            field=models.DateField(default=None),
        ),
    ]
