# Generated by Django 3.1.1 on 2020-09-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0003_biblioteka_data_premiery'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteka',
            name='liczba_stron',
            field=models.IntegerField(default=None),
        ),
    ]
