# Generated by Django 3.1.1 on 2020-09-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0004_biblioteka_liczba_stron'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteka',
            name='zdjecie',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
