# Generated by Django 3.1.1 on 2020-09-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0005_biblioteka_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteka',
            name='zdjecie',
            field=models.FileField(upload_to='zdjecia'),
        ),
    ]
