# Generated by Django 3.1.1 on 2020-09-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0006_auto_20200909_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblioteka',
            name='zdjecie',
        ),
    ]
