# Generated by Django 3.1.1 on 2020-09-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0007_remove_biblioteka_zdjecie'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteka',
            name='zdjecie',
            field=models.FileField(null=True, upload_to='zdjecia'),
        ),
    ]
