# Generated by Django 3.1.1 on 2020-09-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0008_biblioteka_zdjecie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblioteka',
            name='zdjecie',
        ),
    ]
