# Generated by Django 3.1.1 on 2020-09-09 19:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Biblioteka', '0010_biblioteka_zdjecie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biblioteka',
            new_name='Ksiazka',
        ),
    ]
