# Generated by Django 3.1.1 on 2020-09-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0011_auto_20200909_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='zdjecie',
            field=models.FileField(null=True, upload_to='zdjecia/'),
        ),
    ]
