# Generated by Django 3.1.1 on 2020-09-10 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0012_auto_20200910_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='zdjecie',
            field=models.FileField(default=None, upload_to='zdjecia/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
            preserve_default=False,
        ),
    ]
