# Generated by Django 3.1.1 on 2020-09-11 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0015_auto_20200910_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='zdjecie',
            field=models.FileField(default=None, null=True, upload_to='Biblioteka/static/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
    ]
