# Generated by Django 3.1.1 on 2020-09-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0016_auto_20200911_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazka',
            name='czy_aktywna',
            field=models.BooleanField(default=True),
        ),
    ]
