# Generated by Django 3.1.1 on 2020-09-12 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteka', '0017_ksiazka_czy_aktywna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='zdjecie',
            field=models.FileField(default=None, null=True, upload_to='zdjecia', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
    ]
